// ---- Word Lists ----
// Level 1: Visual/concrete objects you can picture
const WORDS_VISUAL = [
    // Animals
    'elephant', 'tiger', 'eagle', 'dolphin', 'butterfly', 'penguin', 'giraffe',
    'octopus', 'parrot', 'whale', 'turtle', 'rabbit', 'spider', 'scorpion',
    'flamingo', 'gorilla', 'cheetah', 'crocodile', 'seahorse', 'owl',
    'peacock', 'jellyfish', 'chameleon', 'koala', 'panda', 'lobster',
    'kangaroo', 'falcon', 'salmon', 'dragonfly',
    // Nature
    'mountain', 'volcano', 'waterfall', 'glacier', 'canyon', 'desert', 'forest',
    'island', 'cave', 'river', 'ocean', 'lake', 'cliff', 'rainbow', 'tornado',
    'lightning', 'avalanche', 'geyser', 'coral', 'iceberg', 'swamp', 'meadow',
    'valley', 'beach', 'sunrise', 'sunset', 'aurora',
    // Food & Drink
    'pizza', 'hamburger', 'spaghetti', 'sushi', 'chocolate', 'pineapple',
    'watermelon', 'strawberry', 'banana', 'apple', 'grapes', 'cherry',
    'mushroom', 'avocado', 'coconut', 'pretzel', 'popcorn', 'cupcake',
    'pancake', 'sandwich', 'taco', 'donut', 'cookie', 'lemon', 'pepper',
    // Objects
    'umbrella', 'telescope', 'microscope', 'compass', 'hourglass', 'lantern',
    'candle', 'mirror', 'scissors', 'hammer', 'wrench', 'ladder', 'anchor',
    'key', 'lock', 'bell', 'crown', 'diamond', 'pearl', 'sword', 'shield',
    'helmet', 'trophy', 'medal', 'flag', 'balloon', 'kite', 'parachute',
    'tent', 'bridge', 'lighthouse', 'windmill', 'fountain', 'statue',
    'pillar', 'throne', 'cage', 'chain', 'rope', 'wheel', 'gear',
    'magnet', 'crystal', 'feather', 'bone', 'skull', 'mask', 'drum',
    'trumpet', 'violin', 'guitar', 'piano', 'harp', 'flute',
    // Vehicles & Transport
    'rocket', 'submarine', 'helicopter', 'sailboat', 'canoe', 'bicycle',
    'motorcycle', 'train', 'tractor', 'ambulance', 'spaceship',
    // Buildings & Structures
    'castle', 'pyramid', 'tower', 'cathedral', 'igloo', 'treehouse', 'cabin',
    'barn', 'skyscraper', 'temple', 'palace', 'fortress', 'dome', 'arch',
    // Body & Clothing
    'ring', 'necklace', 'boot', 'glove', 'hat', 'scarf',
    // Plants
    'cactus', 'sunflower', 'rose', 'tulip', 'bamboo', 'vine', 'fern',
    'acorn', 'pinecone', 'lotus', 'orchid', 'lily', 'daisy', 'ivy',
    // Space
    'planet', 'comet', 'asteroid', 'satellite', 'constellation', 'nebula',
    // Misc visual
    'fire', 'flame', 'smoke', 'wave', 'snowflake', 'icicle', 'cobweb',
    'shadow', 'fog', 'cloud', 'star', 'moon', 'sun', 'stone',
    'book', 'scroll', 'map', 'globe', 'painting', 'photograph', 'puzzle',
];

// Level 2: Abstract concepts, emotions, qualities — harder to "see"
const WORDS_ABSTRACT = [
    // Emotions
    'love', 'fear', 'anger', 'joy', 'grief', 'hope', 'shame', 'pride',
    'envy', 'guilt', 'awe', 'bliss', 'rage', 'calm', 'panic', 'sorrow',
    'delight', 'wonder', 'despair', 'ecstasy', 'longing', 'gratitude',
    'compassion', 'jealousy', 'anxiety', 'serenity', 'nostalgia', 'relief',
    'excitement', 'boredom', 'frustration', 'contentment', 'melancholy',
    // Concepts
    'time', 'truth', 'justice', 'freedom', 'wisdom', 'power', 'peace',
    'chaos', 'order', 'balance', 'harmony', 'destiny', 'fate', 'karma',
    'grace', 'honor', 'courage', 'patience', 'silence', 'infinity',
    'eternity', 'mystery', 'paradox', 'illusion', 'reality', 'memory',
    'imagination', 'intuition', 'instinct', 'reason', 'logic', 'faith',
    'doubt', 'belief', 'knowledge', 'ignorance', 'innocence', 'virtue',
    'spirit', 'soul', 'consciousness', 'awareness', 'presence', 'absence',
    'beginning', 'ending', 'journey', 'purpose', 'meaning', 'existence',
    // Qualities
    'beauty', 'strength', 'weakness', 'warmth', 'coldness', 'darkness',
    'brightness', 'softness', 'sharpness', 'sweetness', 'bitterness',
    'emptiness', 'fullness', 'stillness', 'movement', 'speed', 'weight',
    'depth', 'height', 'distance', 'gravity', 'energy', 'force',
    'rhythm', 'flow', 'tension', 'release', 'growth', 'decay',
    // Actions / States
    'dance', 'flight', 'surrender', 'resistance', 'creation', 'destruction',
    'transformation', 'evolution', 'revolution', 'rebellion', 'devotion',
    'sacrifice', 'forgiveness', 'revenge', 'trust', 'betrayal', 'loyalty',
    'connection', 'solitude', 'unity', 'separation', 'return', 'departure',
    'awakening', 'sleep', 'birth', 'death', 'rebirth', 'healing',
    // Nature concepts
    'thunder', 'storm', 'breeze', 'drought', 'flood', 'erosion', 'tide',
    'dawn', 'dusk', 'twilight', 'midnight', 'horizon', 'echo', 'ripple',
    // Human concepts
    'music', 'art', 'poetry', 'magic', 'miracle', 'legend', 'myth',
    'prophecy', 'ritual', 'ceremony', 'tradition', 'heritage', 'legacy',
    'ambition', 'humility', 'dignity', 'respect', 'glory',
    'victory', 'defeat', 'struggle', 'triumph', 'adventure', 'quest',
];

// ---- Emoji / Image List ----
// ~300 emojis. desc is what the AI judges against.
const IMAGES = [
    // Animals — domestic
    { emoji: '🐶', desc: 'dog' },
    { emoji: '🐱', desc: 'cat' },
    { emoji: '🐭', desc: 'mouse' },
    { emoji: '🐹', desc: 'hamster' },
    { emoji: '🐰', desc: 'rabbit' },
    { emoji: '🐻', desc: 'bear' },
    { emoji: '🐼', desc: 'panda' },
    { emoji: '🐨', desc: 'koala' },
    { emoji: '🐯', desc: 'tiger' },
    { emoji: '🦁', desc: 'lion' },
    { emoji: '🐮', desc: 'cow' },
    { emoji: '🐷', desc: 'pig' },
    { emoji: '🐸', desc: 'frog' },
    { emoji: '🐵', desc: 'monkey' },
    { emoji: '🐔', desc: 'chicken' },
    { emoji: '🐧', desc: 'penguin' },
    { emoji: '🐦', desc: 'bird' },
    { emoji: '🦆', desc: 'duck' },
    { emoji: '🦅', desc: 'eagle' },
    { emoji: '🦉', desc: 'owl' },
    { emoji: '🦇', desc: 'bat' },
    { emoji: '🐺', desc: 'wolf' },
    { emoji: '🐗', desc: 'boar' },
    { emoji: '🐴', desc: 'horse' },
    { emoji: '🦄', desc: 'unicorn' },
    { emoji: '🐝', desc: 'bee' },
    { emoji: '🪱', desc: 'worm' },
    { emoji: '🐛', desc: 'caterpillar' },
    { emoji: '🦋', desc: 'butterfly' },
    { emoji: '🐌', desc: 'snail' },
    { emoji: '🐞', desc: 'ladybug' },
    { emoji: '🐜', desc: 'ant' },
    { emoji: '🪲', desc: 'beetle' },
    { emoji: '🦗', desc: 'cricket' },
    { emoji: '🕷️', desc: 'spider' },
    { emoji: '🦂', desc: 'scorpion' },
    { emoji: '🐢', desc: 'turtle' },
    { emoji: '🐍', desc: 'snake' },
    { emoji: '🦎', desc: 'lizard' },
    { emoji: '🐊', desc: 'crocodile' },
    { emoji: '🐘', desc: 'elephant' },
    { emoji: '🦛', desc: 'hippo' },
    { emoji: '🦏', desc: 'rhino' },
    { emoji: '🐪', desc: 'camel' },
    { emoji: '🦒', desc: 'giraffe' },
    { emoji: '🦘', desc: 'kangaroo' },
    { emoji: '🦬', desc: 'bison' },
    { emoji: '🐃', desc: 'water buffalo' },
    { emoji: '🐄', desc: 'cow' },
    { emoji: '🐎', desc: 'horse' },
    { emoji: '🐑', desc: 'sheep' },
    { emoji: '🐐', desc: 'goat' },
    { emoji: '🦌', desc: 'deer' },
    { emoji: '🐕', desc: 'dog' },
    { emoji: '🐈', desc: 'cat' },
    { emoji: '🦃', desc: 'turkey' },
    { emoji: '🐓', desc: 'rooster' },
    { emoji: '🦚', desc: 'peacock' },
    { emoji: '🦜', desc: 'parrot' },
    { emoji: '🦢', desc: 'swan' },
    { emoji: '🦩', desc: 'flamingo' },
    { emoji: '🕊️', desc: 'dove' },
    { emoji: '🦤', desc: 'dodo' },
    { emoji: '🪶', desc: 'feather' },
    // Sea creatures
    { emoji: '🐳', desc: 'whale' },
    { emoji: '🐬', desc: 'dolphin' },
    { emoji: '🦭', desc: 'seal' },
    { emoji: '🐟', desc: 'fish' },
    { emoji: '🐠', desc: 'tropical fish' },
    { emoji: '🐡', desc: 'blowfish' },
    { emoji: '🦈', desc: 'shark' },
    { emoji: '🐙', desc: 'octopus' },
    { emoji: '🐚', desc: 'shell' },
    { emoji: '🪸', desc: 'coral' },
    { emoji: '🦞', desc: 'lobster' },
    { emoji: '🦀', desc: 'crab' },
    { emoji: '🦑', desc: 'squid' },
    { emoji: '🪼', desc: 'jellyfish' },
    { emoji: '🦐', desc: 'shrimp' },
    // Nature — plants & flowers
    { emoji: '💐', desc: 'bouquet' },
    { emoji: '🌸', desc: 'cherry blossom' },
    { emoji: '🌹', desc: 'rose' },
    { emoji: '🌺', desc: 'hibiscus' },
    { emoji: '🌻', desc: 'sunflower' },
    { emoji: '🌼', desc: 'blossom' },
    { emoji: '🌷', desc: 'tulip' },
    { emoji: '🌱', desc: 'seedling' },
    { emoji: '🪴', desc: 'potted plant' },
    { emoji: '🌲', desc: 'evergreen tree' },
    { emoji: '🌳', desc: 'tree' },
    { emoji: '🌴', desc: 'palm tree' },
    { emoji: '🌵', desc: 'cactus' },
    { emoji: '🍀', desc: 'four leaf clover' },
    { emoji: '🍁', desc: 'maple leaf' },
    { emoji: '🍂', desc: 'fallen leaf' },
    { emoji: '🍃', desc: 'leaf' },
    { emoji: '🪹', desc: 'nest' },
    { emoji: '🍄', desc: 'mushroom' },
    // Nature — sky & weather
    { emoji: '🌍', desc: 'earth' },
    { emoji: '🌙', desc: 'moon' },
    { emoji: '⭐', desc: 'star' },
    { emoji: '🌟', desc: 'glowing star' },
    { emoji: '☀️', desc: 'sun' },
    { emoji: '🌈', desc: 'rainbow' },
    { emoji: '☁️', desc: 'cloud' },
    { emoji: '⛈️', desc: 'thunderstorm' },
    { emoji: '🌪️', desc: 'tornado' },
    { emoji: '🌊', desc: 'wave' },
    { emoji: '❄️', desc: 'snowflake' },
    { emoji: '☃️', desc: 'snowman' },
    { emoji: '🔥', desc: 'fire' },
    { emoji: '💧', desc: 'water drop' },
    { emoji: '🌋', desc: 'volcano' },
    { emoji: '🏔️', desc: 'mountain' },
    // Fruit
    { emoji: '🍎', desc: 'apple' },
    { emoji: '🍊', desc: 'orange' },
    { emoji: '🍋', desc: 'lemon' },
    { emoji: '🍌', desc: 'banana' },
    { emoji: '🍉', desc: 'watermelon' },
    { emoji: '🍇', desc: 'grapes' },
    { emoji: '🍓', desc: 'strawberry' },
    { emoji: '🫐', desc: 'blueberry' },
    { emoji: '🍈', desc: 'melon' },
    { emoji: '🍒', desc: 'cherry' },
    { emoji: '🍑', desc: 'peach' },
    { emoji: '🥭', desc: 'mango' },
    { emoji: '🍍', desc: 'pineapple' },
    { emoji: '🥝', desc: 'kiwi' },
    { emoji: '🥥', desc: 'coconut' },
    { emoji: '🥑', desc: 'avocado' },
    // Vegetables
    { emoji: '🥕', desc: 'carrot' },
    { emoji: '🌽', desc: 'corn' },
    { emoji: '🌶️', desc: 'pepper' },
    { emoji: '🥒', desc: 'cucumber' },
    { emoji: '🥦', desc: 'broccoli' },
    { emoji: '🧅', desc: 'onion' },
    { emoji: '🧄', desc: 'garlic' },
    { emoji: '🥔', desc: 'potato' },
    { emoji: '🍆', desc: 'eggplant' },
    // Food
    { emoji: '🍕', desc: 'pizza' },
    { emoji: '🍔', desc: 'hamburger' },
    { emoji: '🌮', desc: 'taco' },
    { emoji: '🌯', desc: 'burrito' },
    { emoji: '🍟', desc: 'french fries' },
    { emoji: '🍿', desc: 'popcorn' },
    { emoji: '🧀', desc: 'cheese' },
    { emoji: '🥚', desc: 'egg' },
    { emoji: '🍳', desc: 'cooking' },
    { emoji: '🥞', desc: 'pancakes' },
    { emoji: '🍞', desc: 'bread' },
    { emoji: '🥐', desc: 'croissant' },
    { emoji: '🥨', desc: 'pretzel' },
    { emoji: '🍩', desc: 'donut' },
    { emoji: '🍪', desc: 'cookie' },
    { emoji: '🎂', desc: 'birthday cake' },
    { emoji: '🍰', desc: 'cake' },
    { emoji: '🧁', desc: 'cupcake' },
    { emoji: '🍫', desc: 'chocolate' },
    { emoji: '🍬', desc: 'candy' },
    { emoji: '🍭', desc: 'lollipop' },
    { emoji: '🍦', desc: 'ice cream' },
    { emoji: '🍝', desc: 'spaghetti' },
    { emoji: '🍜', desc: 'noodles' },
    { emoji: '🍣', desc: 'sushi' },
    { emoji: '🥟', desc: 'dumpling' },
    { emoji: '🍱', desc: 'bento box' },
    // Drinks
    { emoji: '☕', desc: 'coffee' },
    { emoji: '🍵', desc: 'tea' },
    { emoji: '🧃', desc: 'juice box' },
    { emoji: '🍺', desc: 'beer' },
    { emoji: '🍷', desc: 'wine' },
    { emoji: '🧊', desc: 'ice' },
    // Objects — tools & household
    { emoji: '🔑', desc: 'key' },
    { emoji: '🔒', desc: 'lock' },
    { emoji: '🔔', desc: 'bell' },
    { emoji: '🔨', desc: 'hammer' },
    { emoji: '🪓', desc: 'axe' },
    { emoji: '🔧', desc: 'wrench' },
    { emoji: '🪛', desc: 'screwdriver' },
    { emoji: '⚙️', desc: 'gear' },
    { emoji: '🧲', desc: 'magnet' },
    { emoji: '💡', desc: 'light bulb' },
    { emoji: '🔦', desc: 'flashlight' },
    { emoji: '🕯️', desc: 'candle' },
    { emoji: '🪞', desc: 'mirror' },
    { emoji: '🪜', desc: 'ladder' },
    { emoji: '🧹', desc: 'broom' },
    { emoji: '🪣', desc: 'bucket' },
    { emoji: '⏰', desc: 'alarm clock' },
    { emoji: '⌛', desc: 'hourglass' },
    { emoji: '🧭', desc: 'compass' },
    { emoji: '🔭', desc: 'telescope' },
    { emoji: '🔬', desc: 'microscope' },
    { emoji: '✂️', desc: 'scissors' },
    { emoji: '📎', desc: 'paperclip' },
    { emoji: '📌', desc: 'pushpin' },
    { emoji: '🖊️', desc: 'pen' },
    { emoji: '✏️', desc: 'pencil' },
    { emoji: '📏', desc: 'ruler' },
    // Objects — media & music
    { emoji: '🎸', desc: 'guitar' },
    { emoji: '🎹', desc: 'piano' },
    { emoji: '🥁', desc: 'drum' },
    { emoji: '🎺', desc: 'trumpet' },
    { emoji: '🎻', desc: 'violin' },
    { emoji: '🪈', desc: 'flute' },
    { emoji: '🎤', desc: 'microphone' },
    { emoji: '🎧', desc: 'headphones' },
    { emoji: '📷', desc: 'camera' },
    { emoji: '📺', desc: 'television' },
    { emoji: '📻', desc: 'radio' },
    { emoji: '📞', desc: 'telephone' },
    { emoji: '💻', desc: 'laptop' },
    { emoji: '📚', desc: 'books' },
    { emoji: '📖', desc: 'open book' },
    { emoji: '📰', desc: 'newspaper' },
    { emoji: '🗺️', desc: 'map' },
    { emoji: '🧩', desc: 'puzzle piece' },
    { emoji: '🎲', desc: 'dice' },
    { emoji: '♟️', desc: 'chess piece' },
    { emoji: '🎯', desc: 'target' },
    { emoji: '🎨', desc: 'paint palette' },
    { emoji: '🖼️', desc: 'picture frame' },
    // Symbols & decorative
    { emoji: '❤️', desc: 'heart' },
    { emoji: '💎', desc: 'diamond' },
    { emoji: '👑', desc: 'crown' },
    { emoji: '🏆', desc: 'trophy' },
    { emoji: '🎖️', desc: 'medal' },
    { emoji: '⚖️', desc: 'scales' },
    { emoji: '🛡️', desc: 'shield' },
    { emoji: '⚔️', desc: 'swords' },
    { emoji: '🏹', desc: 'bow and arrow' },
    { emoji: '🪄', desc: 'magic wand' },
    { emoji: '🔮', desc: 'crystal ball' },
    { emoji: '⚱️', desc: 'urn' },
    { emoji: '🪬', desc: 'eye amulet' },
    { emoji: '📿', desc: 'prayer beads' },
    { emoji: '🧿', desc: 'evil eye' },
    // Transport
    { emoji: '🚗', desc: 'car' },
    { emoji: '🚕', desc: 'taxi' },
    { emoji: '🚌', desc: 'bus' },
    { emoji: '🚂', desc: 'train' },
    { emoji: '🚁', desc: 'helicopter' },
    { emoji: '✈️', desc: 'airplane' },
    { emoji: '🚀', desc: 'rocket' },
    { emoji: '🛸', desc: 'flying saucer' },
    { emoji: '⛵', desc: 'sailboat' },
    { emoji: '🚢', desc: 'ship' },
    { emoji: '🚲', desc: 'bicycle' },
    { emoji: '🏍️', desc: 'motorcycle' },
    { emoji: '🛻', desc: 'truck' },
    { emoji: '🚜', desc: 'tractor' },
    { emoji: '🚑', desc: 'ambulance' },
    { emoji: '🚒', desc: 'fire truck' },
    { emoji: '🛶', desc: 'canoe' },
    { emoji: '⛽', desc: 'gas pump' },
    { emoji: '🚦', desc: 'traffic light' },
    { emoji: '⚓', desc: 'anchor' },
    // Buildings & places
    { emoji: '🏠', desc: 'house' },
    { emoji: '🏰', desc: 'castle' },
    { emoji: '🏛️', desc: 'temple' },
    { emoji: '⛪', desc: 'church' },
    { emoji: '🕌', desc: 'mosque' },
    { emoji: '🗼', desc: 'tower' },
    { emoji: '🗽', desc: 'statue of liberty' },
    { emoji: '🏗️', desc: 'construction' },
    { emoji: '🏭', desc: 'factory' },
    { emoji: '🏥', desc: 'hospital' },
    { emoji: '🏫', desc: 'school' },
    { emoji: '🏟️', desc: 'stadium' },
    { emoji: '⛺', desc: 'tent' },
    { emoji: '🏖️', desc: 'beach' },
    { emoji: '🏝️', desc: 'island' },
    { emoji: '🌉', desc: 'bridge' },
    { emoji: '🗻', desc: 'mount fuji' },
    // Sports & activities
    { emoji: '⚽', desc: 'soccer ball' },
    { emoji: '🏀', desc: 'basketball' },
    { emoji: '🏈', desc: 'football' },
    { emoji: '⚾', desc: 'baseball' },
    { emoji: '🎾', desc: 'tennis' },
    { emoji: '🏐', desc: 'volleyball' },
    { emoji: '🏓', desc: 'ping pong' },
    { emoji: '🥊', desc: 'boxing glove' },
    { emoji: '🎣', desc: 'fishing' },
    { emoji: '🏄', desc: 'surfing' },
    { emoji: '🏊', desc: 'swimming' },
    { emoji: '🧗', desc: 'climbing' },
    { emoji: '⛷️', desc: 'skiing' },
    { emoji: '🎿', desc: 'skis' },
    { emoji: '🏂', desc: 'snowboarding' },
    { emoji: '🪂', desc: 'parachute' },
    { emoji: '🎪', desc: 'circus tent' },
    { emoji: '🎠', desc: 'carousel' },
    { emoji: '🎡', desc: 'ferris wheel' },
    { emoji: '🎢', desc: 'roller coaster' },
    // Clothing & accessories
    { emoji: '👒', desc: 'hat' },
    { emoji: '🧢', desc: 'cap' },
    { emoji: '👓', desc: 'glasses' },
    { emoji: '🕶️', desc: 'sunglasses' },
    { emoji: '👔', desc: 'necktie' },
    { emoji: '👗', desc: 'dress' },
    { emoji: '👟', desc: 'shoe' },
    { emoji: '👢', desc: 'boot' },
    { emoji: '🧤', desc: 'gloves' },
    { emoji: '🧣', desc: 'scarf' },
    { emoji: '👜', desc: 'handbag' },
    { emoji: '🎒', desc: 'backpack' },
    { emoji: '💍', desc: 'ring' },
    { emoji: '💄', desc: 'lipstick' },
    { emoji: '🪭', desc: 'fan' },
    { emoji: '☂️', desc: 'umbrella' },
    // Miscellaneous
    { emoji: '🎁', desc: 'gift' },
    { emoji: '🎈', desc: 'balloon' },
    { emoji: '🎀', desc: 'ribbon' },
    { emoji: '🪅', desc: 'pinata' },
    { emoji: '🧸', desc: 'teddy bear' },
    { emoji: '🪆', desc: 'nesting dolls' },
    { emoji: '🪁', desc: 'kite' },
    { emoji: '🏮', desc: 'lantern' },
    { emoji: '🕸️', desc: 'spider web' },
    { emoji: '🦴', desc: 'bone' },
    { emoji: '💀', desc: 'skull' },
    { emoji: '👻', desc: 'ghost' },
    { emoji: '🤖', desc: 'robot' },
    { emoji: '👽', desc: 'alien' },
    { emoji: '🧠', desc: 'brain' },
    { emoji: '👁️', desc: 'eye' },
    { emoji: '🫁', desc: 'lungs' },
    { emoji: '🦷', desc: 'tooth' },
    { emoji: '🌡️', desc: 'thermometer' },
    { emoji: '💊', desc: 'pill' },
    { emoji: '🩹', desc: 'bandage' },
    { emoji: '🧬', desc: 'dna' },
    { emoji: '⚡', desc: 'lightning bolt' },
    { emoji: '💥', desc: 'explosion' },
    { emoji: '🕳️', desc: 'hole' },
    { emoji: '🫧', desc: 'bubbles' },
    { emoji: '🌀', desc: 'spiral' },
    { emoji: '🔱', desc: 'trident' },
    { emoji: '☮️', desc: 'peace sign' },
    { emoji: '☯️', desc: 'yin yang' },
    { emoji: '♾️', desc: 'infinity' },
    { emoji: '⚛️', desc: 'atom' },
    { emoji: '🏴‍☠️', desc: 'pirate flag' },
    { emoji: '🚩', desc: 'red flag' },
    { emoji: '🏳️‍🌈', desc: 'rainbow flag' },
];
